#!/usr/bin/env python
# -*- coding: utf-8 -*-
#Author: liyunteng

import os, sys

if __name__ == '__main__':
    importcmd = 'form %s import main' % os.path.basename(sys.argv[0])
    exec importcmd
    main()
